### ISSUE TITLE
Union member already initialized

### ISSUE THREAD

**Issue by Maddius** [g-truc/glm#502] opened 2016-04-28 08:49 UTC
Recently updated to 0.9.7.4 from a very old version and I'm hitting the following warnings.

`**_'glm::tvec3<float,0>::<unnamed-tag>::r' has already been initialized by another union member in the initializer list, 'glm::tvec3<float,0>::<unnamed-tag>::z'_**`

This is compiling with the MS VS 2013 compiler and it is generated by the following function (a simple repro):

```
float foo()
{
	glm::vec3 bar = glm::vec3(0.0f, 1.0f, 1.0f);

	return glm::length(bar);
}
```

I can choose to ignore the warning but I thought I'd mention my encounter, let me know if you need any more information.

Thanks

**Comment by Groovounet** [comment] 2016-05-03 19:47
Hi,

Could you compile with #define GLM_MESSAGES before including GLM headers and report what the compiler says?

I couldn't reproduce this issue...

Thanks,
Christophe

**Comment by Maddius** [comment] 2016-05-04 13:54
Do you have warning level 3 or greater enabled [https://msdn.microsoft.com/en-us/library/w2a7k47y.aspx](url) ?

**Comment by Groovounet** [comment] 2016-05-04 14:23
Yes

**Comment by Groovounet** [comment] 2016-06-04 16:33
Are you using Microsoft compiler language extensions?

**Comment by Groovounet** [comment] 2016-06-26 20:01
No updated on this bug, closing.

**Closed by Groovounet** 2016-06-26 20:01 UTC
Labels: bug
