### ISSUE TITLE
glm with custom types / physic quantities

### ISSUE THREAD

**Issue by tsoj** [g-truc/glm#813] opened 2018-09-07 16:46 UTC
I want to use glm with custom types. I have a physics library, where i have types like `Length` or `Time`.
If i multiply for example a variable of type `Length` with a variable of type `Length` it returns something of type `Area`.
This is not possible with glm. For example if i want to dot his:
```
glm::tvec3<Velocity, glm::highp> speed;
Time time;
glm::tvec3<Length, glm::highp> length = time*speed;
```
I get an error that can be solved when i customize the *-operator for scalars and vec3:
```
template<typename T1, typename T2, qualifier Q>
GLM_FUNC_QUALIFIER auto operator*(vec<3, T1, Q> const& v, T2 scalar)
{
	return vec<3, decltype(v.x * scalar), Q>(
		v.x * scalar,
		v.y * scalar,
		v.z * scalar);
}
```
Which works with c++17 and I believe it compiles also with c++11.
Would it be reasonable to add that feature to glm?

EDIT: the deduction of the return type of a function works only in c++14

**Comment by Groovounet** [comment] 2018-09-14 11:18
This issue is a duplicate of #532

Thanks for reporting,
Christophe

**Closed by Groovounet** 2018-09-14 11:18 UTC
Labels: feature
