### ISSUE TITLE
Odd warning upon updating to latest commit on master

### ISSUE THREAD

**Issue by floyd-m-chitalu** [g-truc/glm#235] opened 2014-09-05 20:57 UTC
warning C4316: object allocated on the heap may not be aligned 16

Using visual studio 2013
64 bit processor

This warning began to pop as soon as I made the upgrade everything was fine before.

**Comment by chris-stones** [comment] 2015-01-31 14:20
bump for cant alloc a struct on the heap that contains a vec4 or mat4.
are we supposed to override new / delete on all classes containing a vec4 / mat4?
seems like an ugly hack?

**Comment by floyd-m-chitalu** [comment] 2015-01-31 14:56
I am reopening this since others have faced a similar problem

**Comment by marekkijo** [comment] 2015-02-23 21:37
I can confirm that issue, mat4 as a member of the object allocated on a heap causing C4316 warning and can be dangerous if you are using SSE instructions (you use them as I suppose).
Probably have to use aligned_malloc for constructing - there are worse hacks than this.

**Comment by engineer0x47** [comment] 2015-04-19 21:52
Is your code throwing an ERROR or a WARNING (based on the posts, I assume it's a warning, thus not a failure to compile)?  The SSE Specification prefers 16-byte alignment for optimum performance.  This is not a "bug" in the software, it is a design limitation of the hardware.  For more information read the following: https://software.intel.com/en-us/node/532814
If you are not using SSE calls on the struct then you can safely ignore the compiler warning.   As for the inability to allocate a struct on the heap, can you post the code you are having issues with?  It would be easier to test.

**Comment by Ident** [comment] 2015-08-07 16:38
This becomes tideous once you are working on a larger project in which a lot of these types are used across many classes. Overloading the new operator for every class allocated on the heap that has such a member requires a lot of extra code. Is there no "cleaner" solution to this?

**Comment by Groovounet** [comment] 2015-08-07 17:13
What would help is a repro case as so far nobody provided any and I never been able to reproduce this bug.

**Comment by engineer0x47** [comment] 2015-08-08 06:00
This is NOT a bug, this issue needs to be closed.  As described above, the problem is not in the GLM library, but with other software using the GLM library improperly.  _aligned_malloc() MUST be used to guarantee proper structure alignment on the heap.

**Comment by chris-stones** [comment] 2015-08-08 07:06
If this is not a bug, as some are saying,  then the documentation needs to updated.

In order to use glm in a portable way, any c++ struct / class containing certain glm types must override the new operator. Bear in mind inheritance, and classes containing classes containing classes containing glm types.

Personally, in my humble opinion, this makes glm look really ugly.

In my humble opinion, I think that on platforms where malloc is not suitably aligned, and SSE is available and being used, classes like mat4 should internally aligned_malloc its SSE types.

For those who are concerned about a possible performance hit, perhaps we could add a glm::aligned::mat4 ??? Which would make the current assumptions.

Or, add glm::unaligned to detect and internally aligned_malloc its SSE types as mentioned previously.

But I certainly don't want to pass this alignment burden onto users of my code. It makes it harder to argue the case for switching to glm.

Just my humble opinion, thanks for listening.

**Comment by Ident** [comment] 2015-08-08 16:31
@Groovounet , reproduction on my setup (VS2015, regular compile options in x86 for 64-bit Windows) is the following:

    class GlmRepro
    {
        GlmRepro(){ m_matrix = new glm::mat4(); }
    
        glm::mat4* m_matrix;
    };

which creates the aforementioned Warning C4316	:
'glm::tmat4x4<float,0>': object allocated on the heap may not be aligned 16

Is this sufficient for you to reproduce it?

**Comment by Groovounet** [comment] 2015-08-08 22:22
This doesn't reproduce the warning on my machine. VS2015 and in 64 bits.

Compiler options my default.

**Comment by BryceMehring** [comment] 2015-08-09 04:15
@Groovounet, on my machine this warning only pops up when a warning level of 3 or higher is enabled.

**Comment by Groovounet** [comment] 2015-08-09 04:50
It doesn't pop up even with all warnings enabled for me.

If you build GLM unit tests, do you see it?

**Comment by BryceMehring** [comment] 2015-08-09 05:30
When running `test-core_type_mat4x4`, the warning only pops up for me when I enable the `GLM_TEST_ENABLE_MS_EXTENSIONS` cmake option.

**Comment by engineer0x47** [comment] 2015-08-09 07:33
Can someone post what a glm::mat4x4 looks like in memory (I don't have my PC available)?  We need to see the whole shebang, function pointers, v-table, etc.  It's not just a simple array, even though a private col_type value[4] is at the core.  The problem might be because of all the other c++ decorations in the struct.  In either case, if new and delete are to be overridden, the overridden functions should be in the type declaration (type_mat4x4.hpp) and not in developer's code, along the lines of what chris-stones posted.  Also, user code could use _aligned_malloc and free instead of using new and delete, new and delete do not need to be overridden (sure, mixing new/delete and malloc/free might make ugly code).

**Comment by Ident** [comment] 2015-08-09 19:20
I do not have `GLM_TEST_ENABLE_MS_EXTENSIONS` enabled (unless it is enabeld by default) and it pops up anyways. I am currently making some large changes in our own Open Source library so I have no resources available right now to do the memory check you required. I am seriously confused why this warning would not be reconstructable, the setup I have is not "exotic" in any sense as far as I see and clearly others ran into the issue as well. I will try to provide the memory output tomorrow or tuesday.

**Comment by Groovounet** [comment] 2015-08-09 20:21
I manage to reproduce thanks to @BryceMehring feedback.

This issue happens only when using Visual Studio language extension which I typically don't do.

I'll study a fix or workaround.

Thanks,
Christophe

**Comment by Ident** [comment] 2015-08-09 23:08
The language extension is on by default. Just in case anyone wanted to know ( https://msdn.microsoft.com/en-us/library/0k0w269d.aspx )

**Comment by Groovounet** [comment] 2015-08-31 19:47
This issue should be fixed in master branch for GLM 0.9.7.1 release.

Thanks for contributing,
Christophe

**Closed by Groovounet** 2015-08-31 19:47 UTC
Labels: bug

**Comment by floyd-m-chitalu** [comment] 2015-08-31 21:47
Thank you.

**Comment by Ident** [comment] 2015-09-07 13:24
Thank you and I am looking forward to 0.9.7.1 Release.

**Comment by Ident** [comment] 2015-11-29 09:30
A bit late, but I want to confirm that this warning indeed was fixed by the 0.9.7.1 Release. We get zero warnings now from glm, just like we did before this warning started coming up. The fast way this was handled and the good development and stable API compatibility of the library make me feel further assured that it was the right choice to replace our internal math classes and functions by glm ones, making glm our only mandatory dependency for CEGUI :+1:
