### ISSUE TITLE
Support compiler vector extensions

### ISSUE THREAD

**Issue by feliwir** [g-truc/glm#954] opened 2019-09-18 16:37 UTC
Compilers like clang do have vector extension types, which support swizzling and SIMD natively.
E.g. https://clang.llvm.org/docs/LanguageExtensions.html#vectors-and-extended-vectors

This would probably be great for reducing compile times since the required code should be much less.

**Comment by christophe-lunarg** [comment] 2023-12-29 12:37
This looks great but nobody tackle this issue and the issue is now very old so closing...

**Closed by christophe-lunarg** 2023-12-29 12:37 UTC
Labels: CC: gcc, CC: clang, feature, help wanted

**Comment by data-man** [comment] 2023-12-31 06:36
https://en.cppreference.com/w/cpp/experimental/simd
https://www.intel.com/content/www/us/en/developer/articles/technical/vectorization-llvm-gcc-cpus-gpus.html
