### ISSUE TITLE
CUDA compiler error in type_aligned.hpp

### ISSUE THREAD

**Issue by endlessMagic** [g-truc/glm#994] opened 2020-02-18 14:52 UTC
I tried to use the newest version of glm(0.9.9.7) in CUDA for aligned_vec4, I got some compile errors:

CUDA Version: 10.1
C++ Compiler: Visual C++ 2017
Errors:
For many lines like xxx, I got
glm/gtx/aligned_vec4.hpp(xxx): error : expected a ";"

After some investigations, I found that the reason is aligned_vec4 is expanded to

> typedef vec4 aligned_vec4 __declspec(align(x));

Actually, it should be 
> typedef __declspec(align(x)) vec4 aligned_vec4;

So the problem might be that GLM_COMPILER_VC is not defined while defining
> GLM_ALIGNED_TYPEDEF 

in glm/detail/setup.hpp, so a wrong definition for it is chosen.

Could you fix this?

**Comment by christophe-lunarg** [comment] 2023-12-29 12:32
Closing only because no additional comment went in and the issue is very old.

Thanks for reporting and hoping the issue resolved itself!

**Closed by christophe-lunarg** 2023-12-29 12:32 UTC
Labels: CC: cuda
