### ISSUE TITLE
Quaternion elements order inconsistency depending on GLM_LANG_CXXMS_FLAG

### ISSUE THREAD

**Issue by GPopov** [g-truc/glm#934] opened 2019-08-02 14:01 UTC
The order of the w,x,y,z members in quats is not consistent, depending if `GLM_LANG` has the `GLM_LANG_CXXMS_FLAG` set. This currently produces a warning of the type:

> field 'w' will be initialized after field 'x' [-Werror,-Wreorder]
> in instantiation of member function 'glm::qua<float, glm::packed_lowp>::qua' requested here

The incosistency seems to have been introduced in https://github.com/g-truc/glm/commit/abcc46012a8165831832c807f442394c347811c5 

https://github.com/g-truc/glm/blob/947527d3ac1910e62d142c76480293fee460603d/glm/detail/type_quat.hpp#L42-L51

**Comment by pwipf** [comment] 2019-08-07 00:06
I just commented on closed issue #916 before seeing this issue.

Inconsistent order caused by commit f5381ef.

My 2 cents is to roll back to the storage order x,y,z,w, which is consistent with glm::vec4 storage order, and openGL vec4 storage order, and is consistent with other well respected matrix libraries (Eigen).

Please see my comments on issue #916.

**Comment by Groovounet** [comment] 2019-09-07 08:42
This issue has been resolved with #942.

Thanks for reporting !

**Closed by Groovounet** 2019-09-07 08:42 UTC
