### ISSUE TITLE
multiplication of quaternion and vec3

### ISSUE THREAD

**Issue by hukutansk** [g-truc/glm#408] opened 2015-09-18 13:48 UTC
the multiplication operator [in the file "quaternion.inl" at line 319](https://github.com/g-truc/glm/blob/master/glm/gtc/quaternion.inl#L319) is not working right.

**Comment by Groovounet** [comment] 2015-09-28 21:53
What's not working right about it?

**Comment by Groovounet** [comment] 2015-09-30 23:00
"Not working" is not a bug report so closing.

**Closed by Groovounet** 2015-09-30 23:00 UTC
Labels: invalid
