### ISSUE TITLE
Missing operator* for vector classes?

### ISSUE THREAD

**Issue by alexanderbock** [g-truc/glm#843] opened 2018-12-02 05:47 UTC
Given:
```
    glm::ivec2 f;
    float t;
```
`f *= t;` compiles, where as `glm::ivec2 g = f * t;` does not

It looks like the non `*=` version of
```
		template<typename U>
		GLM_FUNC_DECL GLM_CONSTEXPR vec<2, T, Q> & operator*=(U scalar);
```
is missing

**Comment by Groovounet** [comment] 2018-12-30 13:46
This is a duplicate of #532

Thanks for reporting,
Christophe

**Closed by Groovounet** 2018-12-30 13:46 UTC
