### ISSUE TITLE
smoothstep(double, double, float) doesn't compile

### ISSUE THREAD

**Issue by FabriceNeyret** [g-truc/glm#835] opened 2018-11-20 17:04 UTC
more generally, when there is a mix of float and doubles.
Shouldn't they be automatically converted ?

**Comment by Sarvadi** [comment] 2018-12-09 09:44
This is correct. The templated type is ambiguous, so the compiler can't tell if you want `smoothstep<float>` or `smoothstep<double>`. You can fix this by explicitly specifying `smoothstep<double>`, or promoting the float yourself.

**Comment by Groovounet** [comment] 2018-12-30 13:47
This is a duplicate of #532

Thanks for reporting,
Christophe

**Closed by Groovounet** 2018-12-30 13:47 UTC
